"SMTP_SERVER": ["smtp-mail.outlook.com"] #["shibahara.co.jp"]
"SMTP_PORT": ["587"] #["smtp"]
"MAILLIST": 
   "from_addr": ["yamaha.aipicking@outlook.jp"]
   # "from_addr": ["hirao@shibahara.co.jp"]
   "to_addr": ["saitoutakash@yamaha-motor.co.jp"]
   # "to_addr": ["hirao@shibahara.co.jp,komaikek@yamaha-motor.co.jp,yamamotoats@yamaha-motor.co.jp,saitoutakash@yamaha-motor.co.jp"]
   # "to_addr": ["hirao@shibahara.co.jp"]
   "password": ["AiPicking"]
"RUN_UI_PATH": "run/visualize_data"
"NEED_AUTH": [False] #[True]
"DEBUG_FLG": True
"TEXT_STRS":
   "run_ui":
      "error":
         "subject": '【芝原様機 生産】エラー発生 ' 
         "msg": '芝原様機 エラー発生'
      "start":
         "subject": '【芝原様機 生産】生産開始 '
         "msg": '芝原様機 生産開始'
      "done":
         "subject": '【芝原様機 生産】生産完了 '
         "msg": '芝原様機 生産完了'
   "train_ui":
      "error":
         "subject": '【芝原様機 学習UI】エラー発生 ' 
         "msg": '芝原様機 エラー発生'
      "start":
         "subject": '【芝原様機 学習UI】データ収集開始 '
         "msg": '芝原様機 データ収集開始'
      "done":
         "subject": '【芝原様機 学習UI】データ収集完了 '
         "msg": '芝原様機 データ収集完了'
   "pickuptest_ui":
      "error":
         "subject": '【芝原様機 ピックアップテスト】エラー発生 ' 
         "msg": '芝原様機 エラー発生'
      "start":
         "subject": '【芝原様機 ピックアップテスト】ピックアップテスト開始 '
         "msg": '芝原様機 ピックアップテスト開始'
      "done":
         "subject": '【芝原様機 ピックアップテスト】ピックアップテスト完了 '
         "msg": '芝原様機 ピックアップテスト完了'
