version: 1
formatters:
  customFormatter:
    format: '%(asctime)s : %(levelname)s : %(module)s : %(lineno)d : %(message)s'
    datefmt: '%Y-%m-%d_%H:%M:%S'

handlers:
  fh_mailsender:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    filename: logger_mailsender.log
    formatter: customFormatter
    backupCount: 3
    maxBytes: 0

  fh_mailprocess:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    filename: logger_mail_process.log
    formatter: customFormatter
    backupCount: 3
    maxBytes: 0

  consoleHandler:
    class: logging.StreamHandler
    level: DEBUG
    formatter: customFormatter

loggers:
  logger_mailsender:
    level: DEBUG
    handlers: [fh_mailsender, fh_mailprocess, consoleHandler]
    propagate: false

  logger_mail_process:
    level: DEBUG
    handlers: [fh_mailprocess, consoleHandler]
    propagate: false

root:
  level: DEBUG
  handlers: [fh_mailprocess, consoleHandler]
